### ISSUE TITLE
Error upgrading to version 1.5.1 in WordPress

### ISSUE THREAD

**Issue by KilakwaBT** [twomice/com.joineryhq.percentagepricesetfield#42]
When upgrading the extension in WordPress we are getting a WordPress fatal error. The extension seems to update OK. Here are the error details.

```
Error Details
=============
An error of type E_ERROR was caused in line 14 of the file /home/<<account>>/public_html/wp-content/plugins/files/civicrm/extend/com.joineryhq.percentagepricesetfield/settings/Percentagepricesetfield.setting.php. Error message: Uncaught Error: Class 'CRM_Percentagepricesetfield_ExtensionUtil' not found in /home/<<account>>/public_html/wp-content/plugins/files/civicrm/extend/com.joineryhq.percentagepricesetfield/settings/Percentagepricesetfield.setting.php:14
Stack trace:
#0 /home/<<account>>/public_html/wp-content/plugins/civicrm/civicrm/Civi/Core/SettingsMetadata.php(109): include()
#1 /home/<<account>>/public_html/wp-content/plugins/civicrm/civicrm/Civi/Core/SettingsMetadata.php(92): Civi\Core\SettingsMetadata::loadSettingsMetadata('/home/<<account>>/p...')
#2 /home/<<account>>/public_html/wp-content/plugins/civicrm/civicrm/Civi/Core/SettingsMetadata.php(66): Civi\Core\SettingsMetadata::loadSettingsMetaDataFolders(Array)
#3 /home/<<account>>/public_html/wp-content/plugins/civicrm/civicrm/Civi/Core/SettingsManager.php(220): Civi\Core\SettingsMetadata::getMetadata(Array)
#4 /home/<<account>>/public_html/wp-content/plugins/civicrm/civicrm/Civi/Core/SettingsManager.php(316): Civi\Core\SettingsManager->getDefaults('domain')
#5 /home/<<account>>/public_html/wp-content
```

**Comment by lucky091588** [comment]
Thanks @KilakwaBT for creating this ticket. I will check this one.

**Comment by lucky091588** [comment]
Hi @KilakwaBT. Would you let me know the version of the extension you are using before update?

**Comment by chrisgaraffa** [comment]
Just ran into the same thing. CiviCRM 5.9.2, PHP 7.2.24 (I know, we need to update), updated from 1.5.0 to 1.5.1

```
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'CRM_Percentagepricesetfield_ExtensionUtil' not found in <path>/public_html/wp-content/uploads/civicrm/ext/com.joineryhq.percentagepricesetfield/settings/Percentagepricesetfield.setting.php:14
Stack trace:
#0 <path>/public_html/wp-content/plugins/civicrm/civicrm/Civi/Core/SettingsMetadata.php(109): include()
#1 <path>/public_html/wp-content/plugins/civicrm/civicrm/Civi/Core/SettingsMetadata.php(92): Civi\\Core\\SettingsMetadata::loadSettingsMetadata('/mnt/PWSA-Addit...')
#2 <path>/public_html/wp-content/plugins/civicrm/civicrm/Civi/Core/SettingsMetadata.php(66): Civi\\Core\\SettingsMetadata::loadSettingsMetaDataFolders(Array)
#3 <path>/public_html/wp-content/plugins/civicrm/civicrm/Civi/Core/SettingsManager.php(220): Civi\\Core\\SettingsMetadata::getMetadata(Array)
#4 <path>/public_html/wp-content/plugins/civicrm/civicrm/Ci...
', referer: https://<site>/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Fextensions&action=update&id=com.joineryhq.percentagepricesetfield&key=com.joineryhq.percentagepricesetfield
```

Then,
```
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to CRM_Admin_Page_Extensions::createExtendedInfo() must be an instance of CRM_Extension_Info, null given, called in <path>/public_html/wp-content/plugins/civicrm/civicrm/CRM/Admin/Form/Extensions.php on line 74 and defined in <path>/public_html/wp-content/plugins/civicrm/civicrm/CRM/Admin/Page/Extensions.php:332
Stack trace:
#0 <path>/public_html/wp-content/plugins/civicrm/civicrm/CRM/Admin/Form/Extensions.php(74): CRM_Admin_Page_Extensions::createExtendedInfo(NULL)
#1 <path>/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(668): CRM_Admin_Form_Extensions->preProcess()
#2 <path>/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Display.php(76): CRM_Core_Form->buildForm()
#3 <path>/public_html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.ph...
'
```

**Comment by twomice** [comment]
I'm closing this because it's quite old and may no longer be relevant. If this is still an issue you'd like help with, please feel free to re-open this issue.
